### ISSUE TITLE
Implementation of resource based Princeton object (map backed) dictionary available

### ISSUE THREAD

**Issue by plandes** [extjwnl/extjwnl#22]
I have implemented a resource based Princeton object dictionary (reads map backed dictionary) from a resource file.  It also builds the map backed serialization file needed by the implementation and packages in it on nice neat jar file.

Please see the [repo](https://github.com/plandes/wordnet-mapres) and let me know if you have any questions.  The class is in a separate namespace (mine for now), and the map files are also in their own namespace so adding the 1.9.3 deps with this won't conflict.

I'd be happy to fold in my contribution with a pull request if you want.

**Comment by autayeu** [comment]
Hi Paul. This is a fantastic piece of work: well-made, documented, with tests. Thank you for your time!

Given that there are few noticeable differences between the projects (build, logging, packages, etc), let me propose few ways to continue.

One way to continue would be to leave this contribution independent as is. Perhaps one suggestion would be to be consistent and put everything under your own namespace, including data and resource files, so that the usage for end-users reads something like:
```java
Dictionary dict = Dictionary.getResourceInstance("/com/zensols/nlp/wordnet-mapres/.../res_properties.xml");
```
And if you'd like, linking from a suitable extJWNL page to your repo (make a PR, please).

Another way to continue would be to integrate this into the library. However, that might require some more work on your part and on mine. If that suits you, then I'd propose you refactor a bit this contribution and make respective PRs.

I'd propose the following (please, let's discuss if you think differently):
* please, can you explain why there is a need for ```PrincetonResourceObjectDictionaryFile```? I perhaps could spend more time and try to understand, but it might be faster if you explain, what ```PrincetonObjectDictionaryFile``` is missing? It seems like a mix of text-based and map-based.
* I'd split into two repos: the code goes into extjwnl, the data goes into a separate ```extjwnl-data-wn31-map``` repo along the lines with the other ones.
* I'd avoid extra dependencies
* I'd avoid extra build tools

If you'd like to go this way, I've drafted a few files to get you started. I did not test this, it's just to show you possible direction. I think it should work, but I rely on you to try and complete and test this.
* Please, take a look at [resource-map](https://github.com/autayeu/extjwnl/tree/resource-map) branch and in particular, the commit [553dfe8](https://github.com/autayeu/extjwnl/commit/553dfe80752c902bcce49e7c1c04b1403b0d92a3). I think ```PrincetonResourceObjectDictionaryFile``` should do what you'd like.
* Please, take a look at [extjwnl-data-wn31-map](https://github.com/autayeu/extjwnl-data-wn31-map) repo. It's a placeholder for map resources.
* Please, take a look at [extjwnl-utilities pom.xml](https://github.com/extjwnl/extjwnl/blob/master/utilities/pom.xml) lines 118-224 for an example on how to get, unpack and convert dictionary files into serialized map. That could be a template for extjwnl-data-wn31-map.

If this suits you, please, make PRs - against [resource-map](https://github.com/autayeu/extjwnl/tree/resource-map) branch if necessary and against master in [extjwnl-data-wn31-map](https://github.com/autayeu/extjwnl-data-wn31-map). I'll then review, pull, test, push into masters and release.

If something does not make sense, or does not work for you - please, let me know.

Looking forward to your comments and eventually PRs. Thank you.

**Comment by plandes** [comment]
Hi Aliaksandr,

Thanks for your nice words and your in-depth analysis.

I could be missing something, but I saw/understood there to be the following classes:

* Read/write non-serialized/non-map backed files from the file system.
* Read serialized map backed files from the file system.
* Read/write non-serialized/non-map backed files from resource files with `Class.getResourceAsStream`.

However, I couldn't find anything that would read and unserialize a map backed dictionary from a resource.  I think you could probably find a way to use the decorator pattern or some strategy based pattern to separate all this functionality out.  However, then you'd have to fold out your class hierarchy out quiet a bit, so I imagine that's why you didn't.  Of course the downside is some duplicated functionality (again, if I understand).

Regarding how to proceed: any way that's easiest for you.  At the time of writing the Java class, my thought was to just add it to the extjwnl repo and just change to the package name to fit in your class structure.  Then split out the serailized data zip file like the `extjwnl-data-wn31` jar.

Since this is your project and I'm contributing I'm glad to do whatever you think is best.  As long as I can include whatever the result is and have the map backed resource as I'm using it I'll switch to whatever your change will be in the next version of extjwml.

On a side note, the loading of the map backed resource was sub second so this wasn't a big consideration for me since I create one dictionary and share it between threads in a multi-threaded application.

One more thing: `TokenizerOperation.tryAllCombinations` *seems* to have **O(2^n)** (or similar base) exponential time complexity from how long it takes based on string length of size **n**.  However, I haven't done a deep dive on the code.

Regards,
Paul

**Comment by autayeu** [comment]
Hi Paul,

I'm sorry, I wasn't clear enough. By saying "It seems like a mix of text-based and map-based." I meant it was a bit confusing to see some pieces of code like ```getNextLineOffset``` and ```readLine``` that are for text-based files and are not needed for map-based dictionaries.

I've created a branch ```resource-map``` for you in two repos: [autayeu/extjwnl-data-wn31-map](https://github.com/autayeu/extjwnl-data-wn31-map/) and [autayeu/extjwnl](https://github.com/autayeu/extjwnl). Please, can you clone both, checkout the ```resource-map``` branch and then ```mvn clean install``` in ```autayeu/extjwnl``` and then in ```autayeu/extjwnl-data-wn31-map```?
That'll build and install artifacts locally and then you can try including the dependencies like
```xml
<dependency>
    <groupId>net.sf.extjwnl</groupId>
    <artifactId>extjwnl</artifactId>
    <version>1.9.4-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>net.sf.extjwnl</groupId>
    <artifactId>extjwnl-data-wn31-map</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
```
and use the map-backed resource-based dictionary with
```java
Dictionary d = Dictionary.getDefaultResourceInstance();
```
Make sure there is only one artifact with WordNet data in the dependencies.

Please, let me know if this way works for you and if it's what you expected and if it is, I'll release this.

Thank you.

**Comment by autayeu** [comment]
P.S. Yes, ```TokenizerOperation.tryAllCombinations``` is exponential and essentially "hangs" for large "n".

**Comment by plandes** [comment]
Yes it does work and passes all tests.  Looks like you changed the map based word net build process, but a little more credit/attribution other than just a few classes would be nice.

Thanks.

**Comment by autayeu** [comment]
Thank you for testing and confirmation. 

>a little more credit/attribution
Sure. Line 65 in PrincetonResourceObjectDictionaryFile was copied from your code and  I've added you to the authors section. Let me know other places you'd like to mention your name.

**Comment by plandes** [comment]
Great.  Thanks for that.  Yes, I spent time writing nasty POM XML :). Something like resource based maps by Paul Landes and/or refer to my GitHub project.

Thanks @autayeu and for your work on this project.

**Comment by autayeu** [comment]
I've added a link to your Github in the [README.md](https://github.com/extjwnl/extjwnl-data-wn31-map/). I've released the artifacts. The lib is already in Central. I hope the rest will sync there soon.

Thank you for your help. I'm closing this now, but if after your check you feel like something can be improved - please reopen and we'll improve.

**Comment by plandes** [comment]
Perfect!  Also, thanks again for your work on this project.  It's been very helpful in my research.
