### ISSUE TITLE
Error on Documentation Wiki.

### ISSUE THREAD

**Issue by adrrf** [extjwnl/extjwnl#40]
I have found that there is not information on HowToParticipate on the documentation.
Maybe this was intentionally but the documentation doesn't specify.

**Comment by autayeu** [comment]
@adrrf Hi Adrián, thank you for noticing. It was not intentional. There was no much need for such a page: the project is not being actively developed lately (I still maintain it when time permits) and when needed, people just used whatever works for them to reach out or contribute.

Anyway, I've updated HowToParticipate with a first draft. If you have ideas on how to improve it - please, feel free to suggest edits. If you have links to good "HowToParticipate" pages - please, link them. I'll try reviewing and editing when time permits.
