### ISSUE TITLE
Dictionary.lookupIndexWord() stemming can cause a (semi?)infinite loop

### ISSUE THREAD

**Issue by pasky** [extjwnl/extjwnl#5]
With legacy JWNL, lookupIndexWord() behaved differently on multi-word queries than extJWNL - for example, a query "valleys of the mojave desert" would fail with JWNL since there is no such word, but extJWNL apparently tries to grab the first word of the query as a fallback.

(This is somewhat unfortunate from my point of view - I would like a way to apply the stemming but not the new multi-word behavior. But it's probably not that essential.)

The problem is that sometimes this apparently fails in a catastrophic run-away:
```dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'a hot Mediterranean climate (Köppen "Csa"), with subtropical temperatures but a well-defined summer dry season and cool, foggy, rainy season');```
It seems it doesn't like the latter part as 'a well-defined summer dry season and cool, foggy, rainy season' is already non-instant, probably some exponential combinatoric explosion because of the commas?

A groovy script to reproduce:
```groovy
#!/usr/bin/env groovy
@Grab(group='net.sf.extjwnl', module='extjwnl', version='1.8.0')
@Grab(group='net.sf.extjwnl', module='extjwnl-data-wn31', version='1.2')
import net.sf.extjwnl.dictionary.Dictionary;
def dictionary = Dictionary.getDefaultResourceInstance();
println 'a'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'Mediterranean')
println 'b'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'a hot Mediterranean climate');
println 'c'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, '(Köppen "Csa")');
println 'd'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'with subtropical temperatures');
println 'e'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'but a well-defined summer dry season');
println 'f'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'cool, foggy, rainy season');
println 'g'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'a hot Mediterranean climate (Köppen "Csa")');
println 'h'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'a well-defined summer dry season and cool, foggy, rainy season');
println 'i'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'with subtropical temperatures but a well-defined summer dry season and cool, foggy, rainy season');
println '_'
println dictionary.lookupIndexWord(net.sf.extjwnl.data.POS.NOUN, 'a hot Mediterranean climate (Köppen "Csa"), with subtropical temperatures but a well-defined summer dry season and cool, foggy, rainy season');
```

(This works fine with JWNL because it doesn't really do anything special about multi-word queries.)

**Comment by autayeu** [comment]
It seems to me there are two issues here. First, looking up multiwords - whether to look them up by default or not and how. Second, combinatorial explosion.

## Multiword lookup
Original design of the library is very smart and it foresees such cases. Multiword lookup is configurable, see ```<param name="morphological_processor"... ``` section. I've checked with JWNL 1.4-rc2 (I've downloaded it and run a lookup operation) and with current extJWNL and their behaviour is the same:

a test from JWNL 1.4-rc2
```java
public void testMorphological() {
    try {
        JWNL.initialize(TestDefaults.getInputStream());
        iw = Dictionary.getInstance().lookupIndexWord(POS.NOUN, "valleys of the mojave desert");
        System.out.println("Index word : " + iw.toString());

    } catch (JWNLException e) {
        e.printStackTrace();
    }
}
```
output:
```
Jan 16, 2015 12:20:12 PM net.didion.jwnl.util.MessageLog doLog
INFO: Installing dictionary net.didion.jwnl.dictionary.FileBackedDictionary@69ea3742
Index word : [IndexWord: [Lemma: valley] [POS: noun]]
```

The reason is that the morphological processor is configured identically:
```xml
<param name="morphological_processor" value="net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor">
    <param name="operations">
        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
        <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
            <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
            <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
            <param name="adjective" value="|er=|est=|er=e|est=e|"/>
            <param name="operations">
                <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
            </param>
        </param>
        <param value="net.sf.extjwnl.dictionary.morph.TokenizerOperation">
            <param name="delimiters">
                <param value=" "/>
                <param value="-"/>
            </param>
            <param name="token_operations">
                <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
                    <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
                    <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
                    <param name="adjective" value="|er=|est=|er=e|est=e|"/>
                    <param name="operations">
                        <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                    </param>
                </param>
            </param>
        </param>
    </param>
</param>
```
which basically says to apply three operations to the search string:
 * look up search string in exceptions
 * remove suffixes from search string and try again looking up and looking up in exceptions
 * tokenize search string by spaces and dashes and for each token look up, look up in exceptions and recur to detach suffixes like above.

First, it would be nice to understand why in your setup you had different results. One idea: check which configuration files you use and what's inside. Second, you can configure morphological processor to behave as needed. For example, you can remove the whole ```<param value="net.didion.jwnl.dictionary.morph.TokenizerOperation">``` section completely, or just remove tokenization on spaces: ```<param value=" "/>``` or adjust it as needed in some other way, including writing your own operations.

If you use default instance with extJWNL via ```Dictionary.getDefaultResourceInstance();```, it loads configuration from resources and to change that, you will need to extract the configuration file, edit it and configure the instance using your specific configuration.


## Combinatorial explosion
This is indeed what happens. Tokenizer literally tries all combinations in ```TokenizerOperation.tryAllCombinations```. And it takes some :) time. Looking up full sentences (or long and complicated noun phrases) is not a use case for the library, and this behaviour will not be fixed.

You can disable the default tokenizer operation completely or substitute it with the one with different behaviour and adjust your config file.

You might be better off by parsing your sentence first. If you're looking up full sentences in a dictionary, it might indicate that your processing pipeline might need a thought or two. If you're looking up noun phrases, you might be better off by working with the head noun as an approximation of your noun phrase. These and further details depend on the context, on your goal, on the options you have, etc and are relevant for your processing pipeline as a whole rather than the library as a part of it.

Let me know if I can help in any other way.

**Comment by pasky** [comment]
Hi! I see. My configuration file never contained the morphological_section in the first place... Maybe in that case lookup and get was identical operation? (The confusing - for me - configuration system of JWNL was one of the really offputting things and I'm pretty happy that I don't need to care about that anymore with extJWNL.)

Thanks for the great explanation. It all makes sense now, but these details are not at all discoverable from the API docs - so my suggestion here would be to add these details to the lookupIndexWord() documentation, or at least just the fact that you can configure it at all.

Thanks again!

**Comment by autayeu** [comment]
That's a good idea. Thank you!
