### ISSUE TITLE
Can I port the library to c#?

### ISSUE THREAD

**Issue by knuppe** [extjwnl/extjwnl#9]
Hello folks,

I recently ported the apache [opennlp](opennlp.apache.org) library to csharp, as well as an implementation from [Matt Gerber](http://ptl.sys.virginia.edu/ptl/software) that provide smoothly access to the wordnet.

Everything worked perfectly as I expected, but support wordnet is pretty basic... and I would like to replace this implementation to a better one.

So, I would like to know if I have the authorization to port the extjwnl into [my library](https://github.com/knuppe/SharpNL).
Thanks

best regards.
Gustavo K.

**Comment by autayeu** [comment]
Hi Gustavo! I don't know if you need any authorization - the licence should already allow that. Of course you are very welcome to port and I'll help with whatever questions you might have. I don't the best practices about "into my library" part of your question - perhaps it might be better as a separate library (maybe integrated into SharpNL), but you might know better. 

I have only one favor to ask you. Often doing a port involves following the source code quite closely and since you might do that, I'd like to ask you to signal poorly documented or unclear places or otherwise any places that attract your attention as targets for potential improvement. Thank you!

**Comment by knuppe** [comment]
Hi Aliaksandr,

I like to ask as a sign of respect. As devs, we put a lot of life time on codes, I think this is the least sign of respect for our work. :+1: 

About the license, I had doubt because the license on the web site is BSD and in the code did not see any mention of it.

The project will be separated, I was not very clear in the previous message.
I will definitely help if I see something wrong or that can be improved.

Thanks
Gustavo K.

**Comment by autayeu** [comment]
OK, got you :) The license is in license.txt. Good luck with porting!
